name: CI & Deploy to AWS Lambda - Production

on:
  push:
    branches: [ main ]

permissions:
  id-token: write     # ðŸ” Needed for OIDC
  contents: read

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew clean test

      - name: Build Lambda fat JAR
        run: ./gradlew lambdaPackage

      - name: Get JAR name
        id: jar
        run: echo "JAR_NAME=$(ls build/libs/*-lambda.jar)" >> $GITHUB_ENV

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::282616780783:role/uniquora-lambda-access
          aws-region: us-east-1

      - name: Upload JAR to S3
        run: |
          aws s3 cp $JAR_NAME s3://uniquora-jar-bucket/uniquora-lambda.jar

      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code \
          --function-name Uniquora-Backend \
          --s3-bucket uniquora-jar-bucket \
          --s3-key uniquora-lambda.jar \
          --region us-east-1
